### ISSUE TITLE
Suspected inaccurate use of "Badminton" as an activity type

### ISSUE THREAD

**Issue by domfennell** [SportsAndLeisureManagement/opendata#3]
Hi @Sportsandleisuremanagment, we've noticed that some sessions appear to have incorrect `"activity": "prefLabel"` associated with them, for example:

_Serpentine Running Club_ with `"id": "1561K9011900417"` has `"activity": "prefLabel": "Badminton"`;
_50+ Table Tennis_ with `"id": "1563K9013000316"` has `"activity": "prefLabel": "Badminton"`;
_Walkin Hockey_ with `"id": "0832K9010020418"` has `"activity": "prefLabel": "Badminton"`; and
_Young @heart Bowls 13:30_ `"id": "1735K9013300418"` has `"activity": "prefLabel": "Badminton"`.

As a result of this suspected inaccurate recording of data, these sessions will erroneously appear on sport-specific activity finders that we power, e.g. https://www.badmintonengland.co.uk/play/choose-your-court-time/#, as illustrated by the attached screenshot.

![Badminton England activity finder](https://user-images.githubusercontent.com/19166504/48014173-fffef400-e11d-11e8-9774-9eedb696f41d.png)

We also noticed this activity type returns incorrect sessions on your own website. The search term "badminton" returns sessions including walking football, table tennis and bowls (first screenshot below); boxing, forever fit and adult sparring (second screenshot below); and table tennis and serpentine running club (final screenshot below):

<img width="509" alt="screen shot 2018-11-06 at 08 36 44" src="https://user-images.githubusercontent.com/19166504/48053926-c96bbc80-e1a3-11e8-9ae9-bcd948e93e83.png">

<img width="494" alt="screen shot 2018-11-06 at 08 37 25" src="https://user-images.githubusercontent.com/19166504/48053933-ccff4380-e1a3-11e8-96df-c8abce259069.png">

<img width="732" alt="screen shot 2018-11-06 at 09 44 20" src="https://user-images.githubusercontent.com/19166504/48055933-a42d7d00-e1a8-11e8-9336-e81eef7e3ee0.png">

**Comment by Sportsandleisuremanagment** [comment]
Hi Dom, Thank you for feeding this back. This is due to a inputting issue when setting up the class. We are in the process of correcting it.

**Comment by domfennell** [comment]
Hi @Sportsandleisuremanagment, I noticed that some of the offending sessions have been deleted from the OA feed (thanks for this!), e.g. _Serpentine Running Club_ with "id": "1561K9011900417"`, however, a number still erroneously have `"activity": "prefLabel": "Badminton"`, including:

- _50+ Table Tennis_ with `"id": "1563K9013000316"`;
- _Walkin Hockey_ with `"id": "0832K9010020418"`; and
- _Young @heart Bowls 13:30_ with `"id": "1735K9013300418"`.

As a result, these sessions are still appearing on your website and the Badminton England activity finder, as illustrated below:

![screen shot 2018-11-12 at 16 50 56](https://user-images.githubusercontent.com/19166504/48362631-fafcf000-e69b-11e8-893d-827106ffe060.png)

![screen shot 2018-11-12 at 16 56 45](https://user-images.githubusercontent.com/19166504/48362638-fe907700-e69b-11e8-85e8-634c534b4479.png)

**Comment by domfennell** [comment]
Hi @Sportsandleisuremanagment, any news on this?

**Comment by domfennell** [comment]
Hi @Sportsandleisuremanagment, any news on this? (cc @nickevansuk @openactive-bot)
